# 참고 : https://github.com/docker/build-push-action
# https://github.com/docker/setup-buildx-action
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: checkout code
      uses: actions/checkout@v2

    -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} 

    - 
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true


    - 
      name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag lemy0715/nginx-proxy-manager:$(date +%s) \
          --tag lemy0715/nginx-proxy-manager:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64

# steps:
#       - name: checkout code
#         uses: actions/checkout@v2
#       - name: install buildx
#         id: buildx
#         uses: crazy-max/ghaction-docker-buildx@v1
#         with:
#           version: latest
#       - name: build the image
#       run: |
#         docker buildx build \
#           --tag your-username/multiarch-example:latest \
#           --platform linux/amd64,linux/arm/v7,linux/arm64 .

#     - name: login to docker hub
#         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#       - name: build the image
#         run: |
#           docker buildx build --push \
#             --tag your-username/multiarch-example:latest \
#             --platform linux/amd64,linux/arm/v7,linux/arm64 .